run_name: 'tmp'
seg_model_type: 'UNetConvNext'
# convnext_model: 'convnextv2_femto'
# convnext_model_path: './models/convnextv2_femto.safetensors'
aug:
    crop_size:
    - 600
    - 600
    rotate:
        angles:
        - -10
        - 10
    brightness_contrast:
        p: 0.2
    perspective:
        scale:
        - 0.002
        - 0.002
preprocessor:
    size:
    - 768
    - 1380
    use_imagenet_norm: True
dataset:
    batch_size: 6
    workers: 4
train:
    n_epochs: 20
    early_stop_rounds: 5
    eval_strat: 'epoch'
    save_only_best: True
    grad_accum_steps: 1
    max_grad_norm: 1
    optimizer:
        name: 'AdamW'
        params:
            lr: 0.0003
    scheduler:
        name: 'ExponentialLR'
        params:
          gamma: 0.95
    loss:
        dice:
            include_background: False
            squared_pred: False
            jaccard: False
            reduction: 'mean'
            # weight:
                # - 0.01
                # - 1
                # - 1
                # - 1
                # - 1
                # - 1
                # - 1
                # - 1
                # - 1
