[project]
name = "trainloop"
version = "0.1.0"
description = "My simple but handy train loop"
authors = [
    {name = "falkodem",email = "dimbatsula@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch (==2.5.1)",
    "segmentation-models-pytorch (==0.4.0)",
    "torchvision (==0.20.1)",
    "timm (==1.0.11)",
    "opencv-python (>=4.12.0.88,<5.0.0.0)",
    "albumentations (>=2.0.8,<3.0.0)",
    "matplotlib (>=3.10.5,<4.0.0)",
    "joblib (>=1.5.1,<2.0.0)",
    "pycocotools (>=2.0.10,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "trainloop" }]